# Generated by Django 5.1.5 on 2025-01-30 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse_app", "0002_category_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="product_images/"),
        ),
        migrations.AlterField(
            model_name="category",
            name="category_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="warehouse_app.category"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="reorder_quantity",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="product",
            name="reorder_threshold",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="product",
            name="stock_quantity",
            field=models.IntegerField(),
        ),
    ]
