# Generated by Django 5.1.5 on 2025-02-04 14:09

from django.db import migrations


def create_default_categories(apps, schema_editor):
    Category = apps.get_model("warehouse_app", "Category")
    default_categories = [
        "Consumer Electronics",
        "Food and Beverages",
        "Home and Lifestyle",
        "Health and Personal Care",
        "Office Supplies and Stationery",
    ]
    for category_name in default_categories:
        Category.objects.get_or_create(category_name=category_name)


class Migration(migrations.Migration):
    dependencies = [
        (
            "warehouse_app",
            "0003_product_image_alter_category_category_name_and_more",
        ),  # Adjust based on your latest migration
    ]

    operations = [
        migrations.RunPython(create_default_categories),
    ]
