# Generated by Django 5.1.5 on 2025-02-04 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse_app", "0004_auto_20250204_1709"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="reorder_quantity",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="product",
            name="reorder_threshold",
            field=models.PositiveIntegerField(),
        ),
    ]
