# Generated by Django 5.1.5 on 2025-02-12 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse_app", "0007_alter_order_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("processing", "Processing"),
                    ("succeeded", "Succeeded"),
                    ("failed", "Failed"),
                    ("canceled", "Canceled"),
                ],
                default="processing",
                max_length=20,
            ),
        ),
    ]
